project/urls.py
from django.contrib import admin  
from django.urls import path  
from project import views  
urlpatterns = [  
    path('admin/', admin.site.urls),  
    path('emp', views.emp),  
    path('users',views.users),  
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy),  
]  

projectManagement/urls.py
from django.contrib import admin  
from django.urls import path  
from project import views  
urlpatterns = [  
    path('admin/', admin.site.urls),  
    path('emp', views.emp),  
    path('users',views.users),  
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy),  
]  

project/models.py
from django.db import models

# Create your models here.

from django.db import models


class Users(models.Model):
    name = models.CharField(max_length=70, blank=False, default='')
    lastname = models.CharField(max_length=200,blank=False, default='')
    email = models.EmailField()
    class Meta:
        db_table = "user"

project/forms.py
from django import forms  
from project.models import Users
class UserForm(forms.ModelForm):  
    class Meta:  
        model = Users  
        fields = "__all__"  

project/views.py
# Create your views here.
from django.shortcuts import render, redirect  
from project.forms import UserForm  
from project.models import Users  
# Create your views here.  
def emp(request):  
    if request.method == "POST":  
        form = UserForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('users')  
            except:  
                pass  
    else:  
        form = UserForm()  
    return render(request,'index.html',{'form':form})  
def users(request):  
    users = Users.objects.all()  
    return render(request,"users.html",{'users':users})  
def edit(request, id):  
    user = Users.objects.get(id=id)  
    return render(request,'edit.html', {'user':user})  
def update(request, id):  
    user = Users.objects.get(id=id)  
    form = UserForm(request.POST, instance = user)  
    if form.is_valid():  
        form.save()  
        return redirect("users")  
    return render(request, 'edit.html', {'user': user})  
def destroy(request, id):  
    user = Users.objects.get(id=id)  
    user.delete()  
    return redirect("users")  

project/templates/edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<form method="POST" class="post-form" action="/update/{{employee.id}}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Details</h3>  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">User Name:</label>  
    <div class="col-sm-4">  
        <input type="text" name="name" id="id_name" required maxlength="100" value="{{ user.name }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">User Last Name:</label>  
    <div class="col-sm-4">  
        <input type="text" name="lastname" id="id_lastname" required maxlength="254" value="{{ user.lastname }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">User Email:</label>  
    <div class="col-sm-4">  
        <input type="email" name="email" id="id_email" required maxlength="254" value="{{ user.email }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

project/templates/index.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<form method="POST" class="post-form" action="/emp">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Enter Details</h3>  
    </div>  
  </div>   
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">User Name:</label>  
    <div class="col-sm-4">  
      {{ form.name }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">User Last Name:</label>  
    <div class="col-sm-4">  
      {{ form.lastname }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Email:</label>  
    <div class="col-sm-4">  
      {{ form.email }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-primary">Submit</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

project/templates/show.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Users Records</title>  
     {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>  
        <th>User Name</th>  
        <th>User Last Name</th>  
        <th>User Email</th>  


    </tr>  
    </thead>  
    <tbody>  
{% for user in users %}  
    <tr>  
        <td>{{ user.name }}</td>  
        <td>{{ user.lastname }}</td>  
        <td>{{ user.email }}</td>  
        <td>  
            <a href="/edit/{{ user.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>  
            <a href="/delete/{{ user.id }}">Delete</a>  
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  
<center><a href="/emp" class="btn btn-primary">Add New Record</a></center>  
</body>  
</html>  

project/templates/users.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Users Records</title>  
     {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>  
        <th>User Name</th>  
        <th>User Last Name</th>  
        <th>User Email</th>  


    </tr>  
    </thead>  
    <tbody>  
{% for user in users %}  
    <tr>  
        <td>{{ user.name }}</td>  
        <td>{{ user.lastname }}</td>  
        <td>{{ user.email }}</td>  
        <td>  
            <a href="/edit/{{ user.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>  
            <a href="/delete/{{ user.id }}">Delete</a>  
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  
<center><a href="/emp" class="btn btn-primary">Add New Record</a></center>  
</body>  
</html>  